services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: task-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-manager-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-manager-network

  # NestJS Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: task-manager-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      API_PREFIX: api
      DATABASE_URL: postgresql://admin:${DB_PASSWORD:-password123}@postgres:5432/taskmanager?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_TTL: 3600
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      JWT_EXPIRATION: 15m
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-super-secret-refresh-key}
      JWT_REFRESH_EXPIRATION: 7d
      BCRYPT_ROUNDS: 10
      RATE_LIMIT_TTL: 60000
      RATE_LIMIT_MAX: 100
      CORS_ORIGIN: http://localhost:3000,http://localhost:3001
      LOG_LEVEL: debug
      LOG_DIR: ./logs
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
    volumes:
      - .:/app
      - /app/node_modules
      - backend_logs:/app/logs
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - task-manager-network

  # Prisma Studio (Optional - for development)
  prisma-studio:
    image: node:20-alpine
    container_name: task-manager-prisma-studio
    working_dir: /app
    command: sh -c "npm install prisma && npx prisma studio"
    environment:
      DATABASE_URL: postgresql://admin:${DB_PASSWORD:-password123}@postgres:5432/taskmanager?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    networks:
      - task-manager-network
    profiles:
      - tools

# Volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local

# Networks
networks:
  task-manager-network:
    driver: bridge
