apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  redis-host: "redis-service"
  redis-port: "6379"
  jwt-expires-in: "15m"
  cors-origin: "https://taskmanager.io"
  log-level: "info"
  rate-limit-ttl: "60"
  rate-limit-max: "100"
