apiVersion: v1
kind: Namespace
metadata:
  name: task-manager
  labels:
    name: task-manager
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: task-manager-quota
  namespace: task-manager
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: task-manager-limits
  namespace: task-manager
spec:
  limits:
    - max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      type: Container
